Repository Kozea/Radicale, pull requests merged in 2024-10, with the labels that each got.

#1553 pyupgrade --py38-plus
  radicale/config.py
  radicale/server.py
  radicale/types.py
  radicale/utils.py
Labels: task, upcoming incompatibility

#1546 Migrate to pyproject.toml
  pyproject.toml
  setup.cfg
  setup.py
Labels: external packaging, prio:low, improvement

#1589 Fix webcal xml url encoding issue 1582
  radicale/web/internal_data/fn.js
Labels: bug, WebUI

#1592 Fix: only expand VEVENT on REPORT request
  CHANGELOG.md
  radicale/app/report.py
Labels: bug

#1609 log content in case of multiple main components error
  CHANGELOG.md
  radicale/item/filter.py
Labels: improvement

#1610 Rebase galaxy4public patch on top of bf4f5834
  DOCUMENTATION.md
  radicale/auth/__init__.py
  radicale/auth/dovecot.py
  radicale/config.py
  radicale/tests/test_auth.py
Labels: feature, need:reporter feedback, auth
