Repository Kozea/Radicale, pull requests merged in 2024-06, with the labels that each got.

#1511 add support for auth.type=denyall
  CHANGELOG.md
  config
  radicale/auth/__init__.py
  radicale/auth/denyall.py
  radicale/tests/test_auth.py
Labels: improvement

#1512 Warn about default config and no active user authentication
  CHANGELOG.md
  radicale/__init__.py
  radicale/__main__.py
  radicale/auth/__init__.py
  radicale/config.py
Labels: improvement

#1518 Improve verify storage
  radicale/storage/multifilesystem/verify.py
Labels: bug, improvement

#1519 Log exception conditional on debug level
  DOCUMENTATION.md
  config
  radicale/__init__.py
  radicale/__main__.py
  radicale/config.py
  radicale/log.py
Labels: medium, improvement

#1520 add option to skip broken item instead of throwing an exception
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/get.py
Labels: medium, improvement

#1521 Extend and adjust logging options
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/app/base.py
  radicale/config.py
  radicale/httputils.py
  radicale/rights/from_file.py
Labels: low, improvement

#1473 Ability to create predefined calendar or(and) addressbook for new user
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/config.py
Labels: feature

#1522 Apache example configuration from Fedora 41
  contrib/apache/radicale.conf
Labels: documentation

#1525 add "suppress" messages in case debug log options are active
  radicale/app/__init__.py
  radicale/app/base.py
  radicale/app/put.py
  radicale/httputils.py
  radicale/log.py
Labels: low, improvement

#1526 adjust default options for debug log and broken item behavior
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
Labels: cleanup

#1527 extend doc
  DOCUMENTATION.md
Labels: documentation
