Repository Kozea/Radicale, pull requests merged in 2024-11, with the labels that each got.

#1622 Expand taking timezone into account
  radicale/app/report.py
  radicale/tests/static/event_weekly_rrule.ics
  radicale/tests/test_expand.py
Labels: bug

#1624 SSL socket protocol + ciphersuite option
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/server.py
  radicale/utils.py
  setup.cfg
Labels: improvement

#1625 warn of possible client-side SSL requirement
  DOCUMENTATION.md
Labels: documentation

#1627 remove unused dateutil references
  .github/workflows/test.yml
  pyproject.toml
  radicale/storage/__init__.py
  setup.py.legacy
Labels: cleanup

#1631 Improve storage hook
  DOCUMENTATION.md
  config
  radicale/storage/multifilesystem/lock.py
  radicale/tests/test_storage.py
Labels: improvement
