Repository Kozea/Radicale, pull requests merged in 2024-07, with the labels that each got.

#1537 Remove unexpected control codes from ICS files
  radicale/item/__init__.py
Labels: improvement, client

#1538 Workflow test
  .github/workflows/test.yml
  CHANGELOG.md
Labels: upcoming incompatibility

#1541 Modified Reverse-Proxy Examples for Caddy
  DOCUMENTATION.md
Labels: documentation

#1544 Option strip domain name from login
  DOCUMENTATION.md
  config
  radicale/auth/__init__.py
  radicale/config.py
  radicale/tests/test_auth.py
Labels: feature, improvement

#1545 remove setuptools from runtime dependencies
  setup.py
Labels: improvement

#1547 fix misspellings
  radicale/__main__.py
  radicale/app/__init__.py
  radicale/app/propfind.py
  radicale/app/report.py
  radicale/auth/htpasswd.py
  radicale/item/__init__.py
  radicale/item/filter.py
  radicale/rights/from_file.py
  radicale/storage/multifilesystem/get.py
  radicale/tests/__init__.py
  radicale/tests/test_base.py
Labels: task, low

#1548 split tox jobs
  .github/workflows/test.yml
  setup.cfg
Labels: low, improvement

#1549 fix logger-warn-leftovers
  radicale/__init__.py
  radicale/__main__.py
  radicale/server.py
Labels: low, upcoming incompatibility
