Repository Kozea/Radicale, pull requests merged in 2024-03, with the labels that each got.

#1161 Add reverse proxy example for lighttpd
  DOCUMENTATION.md
Labels: documentation

#1244 Add Let's Encrypt Certbot config to Docs
  DOCUMENTATION.md
Labels: documentation

#1252 Fix #715 (Main Component is missing when only recurrence id exists)
  radicale/item/filter.py
Labels: bug

#1273 Update DOCUMENTATION.md: changes permissions
  DOCUMENTATION.md
Labels: bug, documentation

#1305 changed rel="shortcut icon" to rel="icon"
  radicale/web/internal_data/index.html
Labels: feature

#1306 Added html-tags
  radicale/web/internal_data/index.html
Labels: bug

#1310 Document removal of X-Script-Name when serving Radicale at root (/)
  DOCUMENTATION.md
Labels: documentation

#1320 Add example configuration for Caddy web server
  DOCUMENTATION.md
Labels: documentation

#1339 Explain possible pitfall when using git with systemd
  DOCUMENTATION.md
Labels: documentation

#1328 Remove brackets from IPv4 test hostnames
  radicale/tests/test_server.py
Labels: bug

#1303 MOVE on non standard server ports
  DOCUMENTATION.md
  radicale/app/move.py
Labels: bug

#1260 Listen on IPv4 and IPv6
  Dockerfile
Labels: needs reporter feedback

#1365 fix for actions
  radicale/item/__init__.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/cache.py
  radicale/storage/multifilesystem/meta.py
  radicale/storage/multifilesystem/sync.py
  radicale/storage/multifilesystem/upload.py
  radicale/tests/test_server.py
  setup.cfg
Labels: bug

#1092 Hook capability for event changes and deletions
  DOCUMENTATION.md
  config
  radicale/app/base.py
  radicale/app/delete.py
  radicale/app/proppatch.py
  radicale/app/put.py
  radicale/config.py
  radicale/hook/__init__.py
  radicale/hook/none.py
  radicale/hook/rabbitmq/__init__.py
  setup.py
Labels: feature

#1343 Add check for base_prefix indicating Radicale running at site root (/)
  radicale/app/__init__.py
Labels: feature

#1229 Added support for webcal-subscriptions
  radicale/app/propfind.py
  radicale/item/__init__.py
  radicale/xmlutils.py
Labels: feature

#1404 fix for https://github.com/Kozea/Radicale/issues/1350
  config
  radicale/auth/htpasswd.py
Labels: bug

#1409 add option for global permit of delete of collection (default: True t…
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/app/base.py
  radicale/app/delete.py
  radicale/config.py
Labels: feature

#1136 Encode password to allow special characters
  radicale/web/internal_data/fn.js
Labels: bug

#1421 WEB UI: Hide download button for Webcal collections [SMALL]
  radicale/web/internal_data/fn.js
Labels: bug

#1425 auth type "htpasswd" extension for SHA256/SHA512 + autodetect feature
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/auth/htpasswd.py
Labels: feature

#1427 fix for incomplete https://github.com/Kozea/Radicale/pull/1425 and test
  radicale/auth/htpasswd.py
  radicale/tests/test_auth.py
Labels: feature

#1430 be more relaxed on IPv4/IPv6 systems during server listen
  radicale/server.py
Labels: bug

#1431 catch "EBUSY" and move EAI_AGAIN
  radicale/server.py
Labels: bug

#1433 WEB UI: Show collection size [SMALL]
  radicale/web/internal_data/fn.js
Labels: feature

#1435 Fix 1313 by rework server listen code
  radicale/__main__.py
  radicale/server.py
Labels: bug

#1438 extend example and proper format for logged IPv4/IPv6 addresses
  config
  radicale/server.py
Labels: bug, documentation

#1455 improve/extend mkcol logging
  radicale/app/mkcol.py
Labels: improvement

#1456 WEB UI: HREF for Upload, Refresh button, and CSS fixes
  radicale/web/internal_data/css/loading.svg
  radicale/web/internal_data/css/main.css
  radicale/web/internal_data/fn.js
  radicale/web/internal_data/index.html
Labels: feature

#1462 Fix default loglevel and hints
  DOCUMENTATION.md
  config
  radicale/config.py
Labels: improvement
