Repository Kozea/Radicale, pull requests merged in 2024-08, with the labels that each got.

#1552 remove unused requirement "typeguard"
  CHANGELOG.md
  setup.cfg
  setup.py
Labels: cleanup

#1554 hook: gracefully ignore non functional hooks and fall back to none
  radicale/hook/__init__.py
Labels: low, improvement

#1337 Add basic free/busy reporting
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/app/report.py
  radicale/config.py
  radicale/item/filter.py
  radicale/tests/__init__.py
  radicale/tests/static/event10.ics
  radicale/tests/test_base.py
Labels: feature

#1559 Fixes for 3.2.2
  CHANGELOG.md
  DOCUMENTATION.md
  config
  contrib/apache/radicale.conf
  radicale/app/__init__.py
  radicale/app/base.py
  radicale/app/put.py
  radicale/config.py
  radicale/httputils.py
  radicale/rights/from_file.py
Labels: bug, feature, improvement
