Repository Kozea/Radicale, pull requests merged in 2024-09, with the labels that each got.

#1562 Adjustment: option [auth] htpasswd_encryption change default from "md5" to "autodetect"
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
Labels: documentation, task

#1218 Initial version of ldap authentication plugin.
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/auth/__init__.py
  radicale/auth/ldap.py
  radicale/config.py
  radicale/rights/__init__.py
  radicale/rights/from_file.py
  rights
Labels: feature, needs reporter feedback

#1569 Fix changelog link
  v3.html
Labels: documentation

#1570 Fix issue #197
  radicale/auth/ldap.py
Labels: bug, auth:ldap

#1576 Implementing group calendars and increase perfomance
  config
  radicale/app/propfind.py
  radicale/rights/from_file.py
  radicale/storage/__init__.py
  radicale/storage/multifilesystem/discover.py
Labels: improvement, performance

#1579 Implementing ssl connection for ldap auth
  DOCUMENTATION.md
  config
  radicale/auth/ldap.py
  radicale/config.py
Labels: auth:ldap

#1584 permit_delete_collection per collection control
  CHANGELOG.md
  DOCUMENTATION.md
  radicale/app/base.py
  radicale/app/delete.py
  radicale/tests/test_base.py
Labels: feature, improvement

#1585 Add option permit_overwrite_collection
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/app/base.py
  radicale/app/put.py
  radicale/config.py
  radicale/tests/test_base.py
Labels: feature
