Repository Kozea/Radicale, pull requests merged in 2024-12, with the labels that each got.

#1641 Update DOCUMENTATION.md
  DOCUMENTATION.md
Labels: documentation, reverse-proxy:nginx

#1642 Storage cache separation
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/rights/from_file.py
  radicale/storage/__init__.py
  radicale/storage/multifilesystem/__init__.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/cache.py
  radicale/storage/multifilesystem/move.py
  radicale/storage/multifilesystem/upload.py
  radicale/tests/test_storage.py
Labels: feature

#1643 ignore RRULESET if empty in item
  CHANGELOG.md
  radicale/item/filter.py
  radicale/tests/static/event_exdate_without_rrule.ics
  radicale/tests/test_base.py
Labels: improvement, client

#1644 Fixes for Python 3.14
  radicale/httputils.py
Labels: task, upcoming incompatibility

#1648 Cache extension umask fixes
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/storage/multifilesystem/__init__.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/cache.py
  radicale/storage/multifilesystem/delete.py
  radicale/storage/multifilesystem/history.py
  radicale/storage/multifilesystem/move.py
  radicale/storage/multifilesystem/sync.py
  radicale/storage/multifilesystem/upload.py
Labels: feature, improvement

#1650 No cache invalidation on upgrade
  CHANGELOG.md
  radicale/server.py
  radicale/storage/__init__.py
  radicale/utils.py
Labels: improvement, performance

#1651 Show ldap config on startup
  CHANGELOG.md
  radicale/auth/ldap.py
Labels: improvement

#1652 Add: option [auth] uc_username
  CHANGELOG.md
  DOCUMENTATION.md
  radicale/auth/__init__.py
  radicale/config.py
  radicale/tests/test_auth.py
Labels: feature

#1653 Collection cache logging
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/storage/multifilesystem/__init__.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/create_collection.py
  radicale/storage/multifilesystem/get.py
  radicale/storage/multifilesystem/upload.py
Labels: improvement

#1654 Set prodid on collection upload
  CHANGELOG.md
  radicale/app/put.py
Labels: improvement

#1655 Item cache mtime size option
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/config.py
  radicale/storage/multifilesystem/__init__.py
  radicale/storage/multifilesystem/base.py
  radicale/storage/multifilesystem/cache.py
  radicale/storage/multifilesystem/get.py
  radicale/storage/multifilesystem/upload.py
  radicale/tests/test_storage.py
Labels: bug, feature, improvement, performance

#1657 Storage verify nosync / show cache precision
  CHANGELOG.md
  pyproject.toml
  radicale/storage/multifilesystem/__init__.py
  radicale/storage/multifilesystem/verify.py
  setup.py.legacy
Labels: improvement

#1659 Improve: suppress duplicate log lines on startup
  CHANGELOG.md
  radicale/log.py
Labels: improvement

#1660 Show mtime info by default
  radicale/storage/multifilesystem/__init__.py
Labels: improvement

#1663 Contrib: logwatch config and script
  CHANGELOG.md
  contrib/logwatch/radicale
  contrib/logwatch/radicale.conf
Labels: feature

#1664 Fix for Issue 1133
  CHANGELOG.md
  radicale/app/put.py
Labels: improvement
