Repository Kozea/Radicale, pull requests merged in 2024-05, with the labels that each got.

#1480 Update the GNOME setup guide
  DOCUMENTATION.md
Labels: documentation

#1488 Fix missing icons if installed via pip
  setup.py
Labels: bug

#1489 Update pytest
  radicale/tests/__init__.py
  radicale/tests/test_base.py
  radicale/tests/test_config.py
  radicale/tests/test_server.py
  radicale/tests/test_storage.py
  setup.py
Labels: improvement
