Repository Kozea/Radicale, pull requests merged in 2025-06, with the labels that each got.

#1797 Docker publish workflow: Install optional pip dependencies
  .github/workflows/docker-publish.yml
Labels: packaging:container

#1792 Fix binding ldap server.
  radicale/auth/ldap.py
Labels: auth:ldap

#1805 Fix 1803
  CHANGELOG.md
  radicale/storage/multifilesystem/__init__.py
  radicale/tests/test_storage.py
Labels: bug
