Repository Kozea/Radicale, pull requests merged in 2025-05, with the labels that each got.

#1776 Docker publish workflow: Create docker-publish.yml
  .github/workflows/docker-publish.yml
Labels: external packaging

#1779 Docker publish workflow: Add scheduled and workflow_dispatch triggers
  .github/workflows/docker-publish.yml
Labels: packaging:container

#1781 add filtering for VALARM and VFREEBUSY
  CHANGELOG.md
  radicale/item/filter.py
Labels: improvement

#1783 Implement timerange filter for VALARM
  CHANGELOG.md
  radicale/app/report.py
  radicale/auth/htpasswd.py
  radicale/auth/imap.py
  radicale/item/filter.py
  radicale/tests/static/valarm1.ics
  radicale/tests/static/valarm2.ics
  radicale/tests/test_base.py
  radicale/utils.py
Labels: bug, improvement
