Repository Kozea/Radicale, pull requests merged in 2025-07, with the labels that each got.

#1808 Add email notification hook
  DOCUMENTATION.md
  config
  radicale/app/delete.py
  radicale/config.py
  radicale/hook/__init__.py
  radicale/hook/email/__init__.py
  setup.cfg
Labels: feature

#1821 Guard against entries with no vevent_list in the vobject
  radicale/app/report.py
Labels: bug

#1825 Add trace logging feature
  .gitignore
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/__init__.py
  radicale/__main__.py
  radicale/config.py
  radicale/log.py
  radicale/server.py
Labels: improvement

#1830 Fix issue 1826
  CHANGELOG.md
  radicale/utils.py
Labels: bug

#1831 Fix 1824
  CHANGELOG.md
  radicale/item/filter.py
  radicale/storage/__init__.py
  radicale/tests/test_base.py
  radicale/utils.py
Labels: bug

#1832 LDAP auth: protect LDAP search with a try: .. except clause
  radicale/auth/ldap.py
Labels: auth:ldap
