Repository Kozea/Radicale, pull requests merged in 2025-08, with the labels that each got.

#1839 fix-1812-etag
  radicale/app/report.py
Labels: bug

#1844 Fix 1842 storagehooks
  CHANGELOG.md
  DOCUMENTATION.md
  config
  radicale/app/delete.py
  radicale/app/mkcalendar.py
  radicale/app/mkcol.py
  radicale/app/move.py
  radicale/app/proppatch.py
  radicale/app/put.py
  radicale/storage/multifilesystem/lock.py
  radicale/tests/test_storage.py
Labels: bug, feature, improvement

#1829 Improve email notification hook by determining event update type
  DOCUMENTATION.md
  config
  radicale/app/__init__.py
  radicale/app/delete.py
  radicale/app/proppatch.py
  radicale/app/put.py
  radicale/config.py
  radicale/hook/__init__.py
  radicale/hook/email/__init__.py
  radicale/storage/__init__.py
  radicale/storage/multifilesystem/create_collection.py
  radicale/storage/multifilesystem/upload.py
  radicale/tests/test_hook_email.py
Labels: improvement

#1857 Fix broken start when UID does not exist
  radicale/pathutils.py
Labels: improvement
